//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoList.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TaskID { get; set; }
        public string TaskDescription { get; set; }
        public int UserID { get; set; }
        public string ToDoDate { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual User User { get; set; }
    }
}
